// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: protoDataNode/DataNode.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqSaveData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReqSaveData) Reset() {
	*x = ReqSaveData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDataNode_DataNode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSaveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSaveData) ProtoMessage() {}

func (x *ReqSaveData) ProtoReflect() protoreflect.Message {
	mi := &file_protoDataNode_DataNode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSaveData.ProtoReflect.Descriptor instead.
func (*ReqSaveData) Descriptor() ([]byte, []int) {
	return file_protoDataNode_DataNode_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSaveData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ResSaveData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResSaveData) Reset() {
	*x = ResSaveData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDataNode_DataNode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResSaveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResSaveData) ProtoMessage() {}

func (x *ResSaveData) ProtoReflect() protoreflect.Message {
	mi := &file_protoDataNode_DataNode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResSaveData.ProtoReflect.Descriptor instead.
func (*ResSaveData) Descriptor() ([]byte, []int) {
	return file_protoDataNode_DataNode_proto_rawDescGZIP(), []int{1}
}

type ReqData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ReqData) Reset() {
	*x = ReqData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDataNode_DataNode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqData) ProtoMessage() {}

func (x *ReqData) ProtoReflect() protoreflect.Message {
	mi := &file_protoDataNode_DataNode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqData.ProtoReflect.Descriptor instead.
func (*ReqData) Descriptor() ([]byte, []int) {
	return file_protoDataNode_DataNode_proto_rawDescGZIP(), []int{2}
}

func (x *ReqData) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ResData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResData) Reset() {
	*x = ResData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDataNode_DataNode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResData) ProtoMessage() {}

func (x *ResData) ProtoReflect() protoreflect.Message {
	mi := &file_protoDataNode_DataNode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResData.ProtoReflect.Descriptor instead.
func (*ResData) Descriptor() ([]byte, []int) {
	return file_protoDataNode_DataNode_proto_rawDescGZIP(), []int{3}
}

func (x *ResData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ReqShutDown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqShutDown) Reset() {
	*x = ReqShutDown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDataNode_DataNode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqShutDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqShutDown) ProtoMessage() {}

func (x *ReqShutDown) ProtoReflect() protoreflect.Message {
	mi := &file_protoDataNode_DataNode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqShutDown.ProtoReflect.Descriptor instead.
func (*ReqShutDown) Descriptor() ([]byte, []int) {
	return file_protoDataNode_DataNode_proto_rawDescGZIP(), []int{4}
}

type ResShutDown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResShutDown) Reset() {
	*x = ResShutDown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDataNode_DataNode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResShutDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResShutDown) ProtoMessage() {}

func (x *ResShutDown) ProtoReflect() protoreflect.Message {
	mi := &file_protoDataNode_DataNode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResShutDown.ProtoReflect.Descriptor instead.
func (*ResShutDown) Descriptor() ([]byte, []int) {
	return file_protoDataNode_DataNode_proto_rawDescGZIP(), []int{5}
}

func (x *ResShutDown) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_protoDataNode_DataNode_proto protoreflect.FileDescriptor

var file_protoDataNode_DataNode_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x2f,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x67, 0x72, 0x70, 0x63, 0x22, 0x21, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x53, 0x61, 0x76, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0d, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x53, 0x61,
	0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x19, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x22, 0x1d, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x0d, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x53, 0x68, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x22,
	0x21, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x53, 0x68, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0xc7, 0x02, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x31, 0x12,
	0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x71, 0x53, 0x61, 0x76, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x53, 0x61, 0x76,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x32, 0x12, 0x11,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x71, 0x53, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x53, 0x61, 0x76, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x33, 0x12, 0x11, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x71, 0x53, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x53, 0x61, 0x76, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x69, 0x64, 0x12, 0x0d, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x71, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0d, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x69, 0x64, 0x32, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x71, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x26, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x69, 0x64, 0x33, 0x12, 0x0d, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x71, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0d, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x68,
	0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65,
	0x71, 0x53, 0x68, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x72, 0x65, 0x73, 0x53, 0x68, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x42, 0x50, 0x5a, 0x4e,
	0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x53, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x73, 0x2d, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f, 0x73, 0x2d, 0x32, 0x30, 0x32, 0x32, 0x2d, 0x32, 0x2f,
	0x54, 0x61, 0x72, 0x65, 0x61, 0x32, 0x2d, 0x47, 0x72, 0x75, 0x70, 0x6f, 0x30, 0x38, 0x2f, 0x74,
	0x72, 0x65, 0x65, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoDataNode_DataNode_proto_rawDescOnce sync.Once
	file_protoDataNode_DataNode_proto_rawDescData = file_protoDataNode_DataNode_proto_rawDesc
)

func file_protoDataNode_DataNode_proto_rawDescGZIP() []byte {
	file_protoDataNode_DataNode_proto_rawDescOnce.Do(func() {
		file_protoDataNode_DataNode_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoDataNode_DataNode_proto_rawDescData)
	})
	return file_protoDataNode_DataNode_proto_rawDescData
}

var file_protoDataNode_DataNode_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protoDataNode_DataNode_proto_goTypes = []interface{}{
	(*ReqSaveData)(nil), // 0: grpc.reqSaveData
	(*ResSaveData)(nil), // 1: grpc.resSaveData
	(*ReqData)(nil),     // 2: grpc.reqData
	(*ResData)(nil),     // 3: grpc.resData
	(*ReqShutDown)(nil), // 4: grpc.reqShutDown
	(*ResShutDown)(nil), // 5: grpc.resShutDown
}
var file_protoDataNode_DataNode_proto_depIdxs = []int32{
	0, // 0: grpc.DataNodeService.Node1:input_type -> grpc.reqSaveData
	0, // 1: grpc.DataNodeService.Node2:input_type -> grpc.reqSaveData
	0, // 2: grpc.DataNodeService.Node3:input_type -> grpc.reqSaveData
	2, // 3: grpc.DataNodeService.Getid:input_type -> grpc.reqData
	2, // 4: grpc.DataNodeService.Getid2:input_type -> grpc.reqData
	2, // 5: grpc.DataNodeService.Getid3:input_type -> grpc.reqData
	4, // 6: grpc.DataNodeService.ShutDown:input_type -> grpc.reqShutDown
	1, // 7: grpc.DataNodeService.Node1:output_type -> grpc.resSaveData
	1, // 8: grpc.DataNodeService.Node2:output_type -> grpc.resSaveData
	1, // 9: grpc.DataNodeService.Node3:output_type -> grpc.resSaveData
	3, // 10: grpc.DataNodeService.Getid:output_type -> grpc.resData
	3, // 11: grpc.DataNodeService.Getid2:output_type -> grpc.resData
	3, // 12: grpc.DataNodeService.Getid3:output_type -> grpc.resData
	5, // 13: grpc.DataNodeService.ShutDown:output_type -> grpc.resShutDown
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoDataNode_DataNode_proto_init() }
func file_protoDataNode_DataNode_proto_init() {
	if File_protoDataNode_DataNode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoDataNode_DataNode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSaveData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDataNode_DataNode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResSaveData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDataNode_DataNode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDataNode_DataNode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDataNode_DataNode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqShutDown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDataNode_DataNode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResShutDown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoDataNode_DataNode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoDataNode_DataNode_proto_goTypes,
		DependencyIndexes: file_protoDataNode_DataNode_proto_depIdxs,
		MessageInfos:      file_protoDataNode_DataNode_proto_msgTypes,
	}.Build()
	File_protoDataNode_DataNode_proto = out.File
	file_protoDataNode_DataNode_proto_rawDesc = nil
	file_protoDataNode_DataNode_proto_goTypes = nil
	file_protoDataNode_DataNode_proto_depIdxs = nil
}
